<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: andresrobinson
 * Date: Tue, 02 Feb 2016 21:04:39 -0300
 */

$conf['title'] = 'Desarrollo Web - IVAO Argentina';
$conf['start'] = 'api';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['proxy']['user'] = 'andres.robinson@ivao.aero';
$conf['proxy']['pass'] = '<b>WGp1am5BWXNFeg==';

// end auto-generated content
